# -*- coding: utf-8 -*-
"""final_hybrid_modelsl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eZJz2Jdal4OqxFjWdQdQBuVZ6hvcBkF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import warnings
warnings.filterwarnings("ignore")

import tensorflow
from tensorflow import keras
from tensorflow.keras.layers import LSTM,Bidirectional,GRU,SimpleRNN,Dense,Flatten,Input,Embedding,Lambda
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# loading dataset
data = pd.read_csv("train.csv")
data.sample(2)

new_df = data

new_df.shape

new_df.isnull().sum()

new_df.dropna(inplace=True)

new_df.duplicated().sum()

new_df.drop_duplicates(inplace=True)

new_df.duplicated().sum()

# lower case
new_df["question1"] = new_df["question1"].str.lower()
new_df["question2"] = new_df["question2"].str.lower()

new_df.sample(3)

import re
def replace_special_char(q):

    q = q.replace('$', ' dollar ')
    q = q.replace('₹', ' rupee ')
    q = q.replace('€', ' euro ')
    q = q.replace('@', ' at ')

    # The pattern '[math]' appears around 900 times in the whole dataset.
    q = q.replace('[math]', '')

    # Replacing some numbers with string equivalents (not perfect, can be done better to account for more cases)
    q = q.replace(',000,000,000 ', 'b ')
    q = q.replace(',000,000 ', 'm ')
    q = q.replace(',000 ', 'k ')
    q = re.sub(r'([0-9]+)000000000', r'\1b', q)
    q = re.sub(r'([0-9]+)000000', r'\1m', q)
    q = re.sub(r'([0-9]+)000', r'\1k', q)
    return q

new_df["question1"] = new_df["question1"].apply(replace_special_char)
new_df["question2"] = new_df["question2"].apply(replace_special_char)

# remove_html_tage
def remove_html_tage(text):
  pattern = re.compile("<.*?>")
  return pattern.sub("",text)

new_df["question1"] = new_df["question1"].apply(remove_html_tage)
new_df["question2"] = new_df["question2"].apply(remove_html_tage)

contractions = {
        "ain't": "am not",
        "aren't": "are not",
        "can't": "can not",
        "can't've": "can not have",
        "'cause": "because",
        "could've": "could have",
        "couldn't": "could not",
        "couldn't've": "could not have",
        "didn't": "did not",
        "doesn't": "does not",
        "don't": "do not",
        "hadn't": "had not",
        "hadn't've": "had not have",
        "hasn't": "has not",
        "haven't": "have not",
        "he'd": "he would",
        "he'd've": "he would have",
        "he'll": "he will",
        "he'll've": "he will have",
        "he's": "he is",
        "how'd": "how did",
        "how'd'y": "how do you",
        "how'll": "how will",
        "how's": "how is",
        "i'd": "i would",
        "i'd've": "i would have",
        "i'll": "i will",
        "i'll've": "i will have",
        "i'm": "i am",
        "i've": "i have",
        "isn't": "is not",
        "it'd": "it would",
        "it'd've": "it would have",
        "it'll": "it will",
        "it'll've": "it will have",
        "it's": "it is",
        "let's": "let us",
        "ma'am": "madam",
        "mayn't": "may not",
        "might've": "might have",
        "mightn't": "might not",
        "mightn't've": "might not have",
        "must've": "must have",
        "mustn't": "must not",
        "mustn't've": "must not have",
        "needn't": "need not",
        "needn't've": "need not have",
        "o'clock": "of the clock",
        "oughtn't": "ought not",
        "oughtn't've": "ought not have",
        "shan't": "shall not",
        "sha'n't": "shall not",
        "shan't've": "shall not have",
        "she'd": "she would",
        "she'd've": "she would have",
        "she'll": "she will",
        "she'll've": "she will have",
        "she's": "she is",
        "should've": "should have",
        "shouldn't": "should not",
        "shouldn't've": "should not have",
        "so've": "so have",
        "so's": "so as",
        "that'd": "that would",
        "that'd've": "that would have",
        "that's": "that is",
        "there'd": "there would",
        "there'd've": "there would have",
        "there's": "there is",
        "they'd": "they would",
        "they'd've": "they would have",
        "they'll": "they will",
        "they'll've": "they will have",
        "they're": "they are",
        "they've": "they have",
        "to've": "to have",
        "wasn't": "was not",
        "we'd": "we would",
        "we'd've": "we would have",
        "we'll": "we will",
        "we'll've": "we will have",
        "we're": "we are",
        "we've": "we have",
        "weren't": "were not",
        "what'll": "what will",
        "what'll've": "what will have",
        "what're": "what are",
        "what's": "what is",
        "what've": "what have",
        "when's": "when is",
        "when've": "when have",
        "where'd": "where did",
        "where's": "where is",
        "where've": "where have",
        "who'll": "who will",
        "who'll've": "who will have",
        "who's": "who is",
        "who've": "who have",
        "why's": "why is",
        "why've": "why have",
        "will've": "will have",
        "won't": "will not",
        "won't've": "will not have",
        "would've": "would have",
        "wouldn't": "would not",
        "wouldn't've": "would not have",
        "y'all": "you all",
        "y'all'd": "you all would",
        "y'all'd've": "you all would have",
        "y'all're": "you all are",
        "y'all've": "you all have",
        "you'd": "you would",
        "you'd've": "you would have",
        "you'll": "you will",
        "you'll've": "you will have",
        "you're": "you are",
        "you've": "you have",
        "'ve" : "have",
        "n't" : "not",
        "'re" : "are",
        "'ll" : "will"
    }

#  chat_words
def chat_words_handling(text):
  li = []
  if isinstance(text,str):
    for word in text.split():
      if word in contractions:
        li.append(contractions[word])
      else:
        li.append(word)
  return " ".join(li)

new_df["question1"] = new_df["question1"].apply(chat_words_handling)
new_df["question2"] = new_df["question2"].apply(chat_words_handling)

pun = string.punctuation
pun

# remove punctuation
def remove_punctuation(text):
  if isinstance(text,str):
    return text.translate(str.maketrans("","",pun))

new_df["question1"] = new_df["question1"].apply(remove_punctuation)
new_df["question2"] = new_df["question2"].apply(remove_punctuation)

# lenght of the sequences
new_df['q1_len_cha'] = new_df['question1'].str.len()
new_df['q2_len_cha'] = new_df['question2'].str.len()

new_df.head(3)

# len of word
def len_word(text):
  if isinstance(text,str):
    word_len = len(text.split(" "))
    return word_len

new_df['q1_word'] = new_df['question1'].apply(len_word)
new_df['q2_word'] = new_df['question2'].apply(len_word)

new_df.head(3)

new_df["total_words"] = new_df["q1_word"] + new_df["q2_word"]

new_df.head(3)

# difference in words
new_df["different_words"] = new_df["q1_word"] - new_df["q2_word"]

new_df["ration_q1_q2"] = np.round(new_df["q1_word"] / new_df["q2_word"],2)

new_df.head(3)

def common_word(text):
    w1 = set(map(lambda word : word.lower().strip(), text["question1"].split(" ")))
    w2 = set(map(lambda word : word.lower().strip(), text["question2"].split(" ")))
    return len(w1 & w2)

new_df["word_common"] = new_df.apply(common_word,axis=1)
new_df.head(3)

new_df["word_share"] = round(new_df["word_common"]/new_df["total_words"],2)

!pip install rapidfuzz

from rapidfuzz import fuzz

new_df["ratio"] = np.round(new_df.apply(lambda x : fuzz.ratio(x["question1"],x['question2']),axis=1),2)
new_df["partial_ratio"] = np.round(new_df.apply(lambda x : fuzz.partial_ratio(x["question1"],x["question2"]),axis = 1),2)
new_df["token_sort"] = np.round(new_df.apply(lambda x : fuzz.token_sort_ratio(x["question1"],x['question2']),axis = 1),2)
new_df["token_set"] = np.round(new_df.apply(lambda x : fuzz.token_set_ratio(x["question1"],x['question2']),axis = 1),2)

new_df.head(3)

feature = new_df.drop(columns = ["id","qid1","question1","question2","qid2","is_duplicate"],axis=1).values

feature.shape

from sklearn.feature_extraction.text import TfidfVectorizer

# create TF-IDF object
tfidf = TfidfVectorizer(
    ngram_range=(1,2),   # unigrams + bigrams
    max_features=20000,  # vocabulary size
    min_df=2             # ignore rare words
)

# fit on question1 + question2 combined
all_questions = list(new_df["question1"]) + list(new_df["question2"])
tfidf.fit(all_questions)

# transform separately
q1_tfidf = tfidf.transform(new_df["question1"])
q2_tfidf = tfidf.transform(new_df["question2"])

import pickle
# save tfidf
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

cos_sim = (q1_tfidf.multiply(q2_tfidf)).sum(axis=1).A1

cos_sim.shape

feature = np.hstack((feature, cos_sim.reshape(-1,1)))

feature.shape

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features = scaler.fit_transform(feature)

# save scaler
pickle.dump(scaler, open("scaler.pkl", "wb"))

# Deep learning part

all_questions = list(new_df["question1"]) + list(new_df["question2"])

tokenizer = Tokenizer()
tokenizer.fit_on_texts(all_questions)

# save tokenizer
pickle.dump(tokenizer, open("tokenizer.pkl", "wb"))

seq1 = tokenizer.texts_to_sequences(new_df["question1"])
seq2 = tokenizer.texts_to_sequences(new_df["question2"])

max_len = max(
    max(len(seq) for seq in seq1),
    max(len(seq) for seq in seq2)
              )
max_len

q1_pad_seq = pad_sequences(seq1,maxlen=max_len,padding="post")
q2_pad_seq = pad_sequences(seq2,maxlen=max_len,padding="post")

q1_pad_seq.shape

q2_pad_seq.shape

y = new_df["is_duplicate"].values
y

x = [q1_pad_seq,q2_pad_seq]

from sklearn.model_selection import train_test_split
x1_train,x1_test,x2_train,x2_test,x3_train,x3_test,y_train,y_test = train_test_split(
    q1_pad_seq,
    q2_pad_seq,
    features,
    y,
    test_size=0.2,
    random_state=42
)

voc_size = len(tokenizer.word_index)+1
voc_size

from tensorflow.keras.layers import Lambda, Multiply,Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import BatchNormalization

from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
# Hybrid model building
# Input

input1 = Input(shape=(max_len,))
input2 = Input(shape=(max_len,))
input3 = Input(shape=(features.shape[1],))

# Embedding
embedding = Embedding(input_dim=voc_size,output_dim=128)
x1 = embedding(input1)
x2 = embedding(input2)

# shared_lstm = tensorflow.keras.Sequential(
#     [
#         Bidirectional(LSTM(64, return_sequences=True)),
#         Dropout(0.5),
#         Bidirectional(LSTM(32, return_sequences=True)),
#         Dropout(0.4),
#         Bidirectional(LSTM(16))
#   ])
# v1 = shared_lstm(x1)

# v2 = shared_lstm(x2)


# diff = Lambda(lambda x : tensorflow.abs(x[0] - x[1]))([v1,v2])
# mul  = Multiply()([v1, v2])

# lstm_features = Concatenate()([v1,v2,diff,mul])
# lstm_features = BatchNormalization()(lstm_features)

# # ML feature branch
# feat_dense = Dense(8,activation="relu")(input3)
# feat_dense = Dropout(0.5)(feat_dense)
# feat_dense = BatchNormalization()(feat_dense)

# # combine both
# merged = Concatenate()([lstm_features, feat_dense])
# merged = BatchNormalization()(merged)
# merged = Dropout(0.4)(merged)
# # Final layers

# dense = Dense(64, activation='relu',kernel_regularizer=l2(0.0003))(merged)
# dense = Dropout(0.3)(dense)
# dense = Dense(32,activation='relu',kernel_regularizer=l2(0.00002))(dense)
# dense = Dropout(0.4)(dense)
# dense = Dense(16, activation='relu',kernel_regularizer=l2(0.003))(dense)
# dense = Dropout(0.4)(dense)

# # output
# output = Dense(1,activation="sigmoid")(dense)

# # model

# model = Model(inputs=[input1,input2,input3],outputs=output)

# LSTM branch
shared_lstm = tensorflow.keras.Sequential([
    Bidirectional(LSTM(64, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(32))
])

v1 = shared_lstm(x1)
v2 = shared_lstm(x2)

diff = Lambda(lambda x: tensorflow.abs(x[0] - x[1]))([v1, v2])
mul  = Multiply()([v1, v2])

lstm_features = Concatenate()([v1, v2, diff, mul])
lstm_features = Dropout(0.3)(lstm_features)

# ✅ ML branch (STRONGER)
feat_dense = Dense(64, activation="relu",kernel_regularizer=l2(0.0002))(input3)
feat_dense = BatchNormalization()(feat_dense)
feat_dense = Dropout(0.2)(feat_dense)

# merge
merged = Concatenate()([lstm_features, feat_dense])
merged = BatchNormalization()(merged)


merged = Dense(128,activation="relu",kernel_regularizer=l2(0.0002))(merged)
merged = BatchNormalization()(merged)
merged = Dropout(0.2)(merged)

# final layers
dense = Dense(64, activation='relu', kernel_regularizer=l2(0.0002))(merged)
dense = BatchNormalization()(dense)
dense = Dropout(0.3)(dense)

dense = Dense(32, activation='relu', kernel_regularizer=l2(0.0002))(dense)
dense = BatchNormalization()(dense)
dense = Dropout(0.3)(dense)

output = Dense(1, activation='sigmoid')(dense)

model = Model(inputs=[input1, input2, input3], outputs=output)

model.summary()

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor = "val_loss",
    patience = 3,
    restore_best_weights=True,
    verbose = 1
)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.array([0,1]),
    y=y_train
)

class_weights = {0: class_weights[0], 1: class_weights[1]}

history = model.fit(
    [x1_train, x2_train, x3_train],
    y_train,
    validation_data=([x1_test, x2_test, x3_test], y_test),
    epochs=20,
    batch_size=32,
    callbacks=[early_stop],
    class_weight=class_weights
)

# save model
model.save("model.h5")

import matplotlib.pyplot as plt
plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])

from sklearn.metrics import log_loss,accuracy_score,confusion_matrix,classification_report
y_pred = model.predict([x1_test, x2_test,x3_test])

logloss = log_loss(y_test, y_pred)

print("Log Loss:", logloss)

from sklearn.metrics import log_loss,accuracy_score,confusion_matrix,classification_report

from sklearn.metrics import classification_report

y_pred1 = model.predict([x1_test, x2_test, x3_test])

# convert probabilities to 0/1
y_pred1 = (y_pred1 > 0.4).astype(int)

print(classification_report(y_test, y_pred1))

confusion_matrix(y_test, y_pred1)

accuracy_score(y_test, y_pred1)

new_df["is_duplicate"].value_counts()

import numpy as np
from sklearn.metrics import f1_score

y_pred_prob = model.predict([x1_test, x2_test, x3_test])

best_thresh = 0
best_f1 = 0

for t in np.arange(0.2, 0.6, 0.02):
    y_pred = (y_pred_prob > t).astype(int)
    f1 = f1_score(y_test, y_pred)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print("Best Threshold:", best_thresh)
print("Best F1:", best_f1)

from sklearn.metrics import classification_report, log_loss

print(classification_report(y_test, y_pred))
print("Log loss:", log_loss(y_test, y_pred_prob))

from google.colab import files
files.download("model.h5")

from google.colab import files

files.download("tokenizer.pkl")
files.download("tfidf.pkl")
files.download("scaler.pkl")

model.save("model1.keras")

files.download("model1.keras")